name: Latest blog post workflow
on:
  schedule:
    # Runs every hour, on the hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-blog-posts:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update latest posts
        uses: gautamkrishnar/blog-post-workflow@1.8.4
        with:
          feed_list: "https://aldrichtr.github.io/index.xml"
          max_post_count: 5
